### ISSUE TITLE
FastQC node not working with space in file path

### ISSUE THREAD

**Issue by sarahet** [ibisngs/knime4ngs-src#2]
Hi everyone,

I wanted to report that there might be an issue with the FastQC node as it is not properly working for me when file path contains a space somewhere (for example "/home/user/test this/my_read_file.fastq"). In this case only the "my_read_file.FastQC.klock" file is written to the input directory but neither the filter file nor the result folder. Just to mention, I used the FileLoader node to load the fastq file and tried the same fastq file with a path containing a space and a path without (I'm using linux).

**Comment by paulhager** [comment]
The new workflow uses FastQC_v2 and TrimGalore for read filtering and quality control. The old fastqc is deprecated. This bug has been fixed in FastQC_v2 and TrimGalore nodes.
